name: mvvm_mvi_tasks
description: Experimento comparativo MVVM vs MVI em Flutter Web.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.0
  flutter_bloc: ^8.1.0
  bloc: ^8.1.0
  equatable: ^2.0.5
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
